/* tien-do/text/de.mjs — chữ TĨNH của trang tiến độ tiếng Đức (/de/fortschritt/), cùng hình dạng
 * với en.mjs. Chữ JS điền lúc chạy nằm ở `progress` trong i18n/ui.de.js. `{n}` = số bài. */
export default {
  slug: 'fortschritt',
  title: 'Dein Fortschritt im Zehnfingersystem | TypingEase',
  description: 'So läuft dein Schreibtraining: jede Lektion mit Wertung, dein bestes Tempo und deine beste Genauigkeit, eine Heatmap der Tasten, die dir danebengehen, deine Tagesserie und dein Tagesziel.',
  keepLearning: 'Weiterlernen',
  eyebrow: 'Wo du gerade stehst',
  h1: 'Dein Fortschritt im Zehnfingersystem',
  intro: 'Alle Zahlen auf dieser Seite liegen nur auf diesem Gerät und werden nirgendwohin geschickt. Schreib noch eine Lektion, und sie aktualisieren sich.',
  courseSwitch: 'Kurs',
  overviewAria: 'Überblick',
  sumLessons: 'Lektionen geschafft',
  sumStars: 'Gesammelte Sterne',
  sumWpm: 'Bestes WPM',
  sumAccuracy: 'Beste Genauigkeit',
  milestones: 'Meilensteine',
  badgesTitle: 'Abzeichen',
  badgesIntro: 'Jedes Abzeichen hängt an einer echten Zahl aus der Tabelle unten — freischalten kannst du es nur, indem du schreibst.',
  goalKicker: 'Tagesziel',
  goalAria: 'Tagesziel wählen',
  minutes: n => `${n} Min`,
  coachKicker: 'Dein Coach',
  coachTitle: 'Wo du stehst',
  trendAria: 'Letzte Fortschritte',
  keyByKey: 'Taste für Taste',
  heatTitle: 'Heatmap der Tastatur',
  heatText: 'Grüne Tasten triffst du sauber, gelbe mal so, mal so, und rote kosten dich Tempo. Eine Taste bekommt erst eine Farbe, wenn du sie oft genug geschrieben hast, dass die Zahl etwas aussagt.',
  heatEmpty: 'Noch zu wenig Daten — schreib ein paar Lektionen und schau dann wieder vorbei.',
  heatAria: 'Genauigkeit pro Taste',
  courseKicker: 'Der Kurs mit {n} Lektionen',
  resultsTitle: 'Jede Lektion mit Wertung',
  resultsIntro: 'Dein bester Durchgang in jeder Lektion, gespeichert auf diesem Gerät.',
  clear: 'Verlauf löschen',
  columns: ['Lektion', 'Bildschirme geschafft', 'Sterne', 'Bestes WPM', 'Genauigkeit'],
  keepGoing: 'Weitermachen',
  nextTitle: 'Wie es weitergeht',
  courseCard: ['Der ganze Kurs', 'Alle Einheiten der Reihe nach. Nimm dir eine Lektion noch einmal vor oder öffne die nächste Einheit schon früher.', 'Kurs ansehen'],
  layoutsCard: ['Auf deiner eigenen Tastatur', 'QWERTZ, QWERTY, AZERTY, Devanagari, Arabisch, JIS — 119 echte Tastaturbelegungen, und der Kurs folgt der, die du wählst.', 'Belegungen ansehen']
};
