/* tien-do/text/es.mjs — chữ TĨNH của trang tiến độ tiếng Tây Ban Nha (cùng hình dạng với en.mjs).
 * `{n}` = số bài của khoá đang xem. */
export default {
  slug: 'progreso',
  title: 'Tu progreso en mecanografía | TypingEase',
  description: 'Mira cómo avanzas: la nota de cada lección, tus mejores PPM y tu mejor precisión, un mapa de calor de las teclas que fallas, tu racha de días y tu objetivo diario.',
  keepLearning: 'Sigue aprendiendo',
  eyebrow: 'Cómo vas',
  h1: 'Tu progreso en mecanografía',
  intro: 'Todos los números de esta página se guardan en este dispositivo y no se envían a ningún sitio. Haz una lección más y se actualizan.',
  courseSwitch: 'Curso',
  overviewAria: 'Resumen',
  sumLessons: 'Lecciones hechas',
  sumStars: 'Estrellas reunidas',
  sumWpm: 'Mejores PPM',
  sumAccuracy: 'Mejor precisión',
  milestones: 'Metas alcanzadas',
  badgesTitle: 'Insignias',
  badgesIntro: 'Cada insignia depende de un número real de la tabla de abajo — la única forma de conseguirla es escribiendo.',
  goalKicker: 'Objetivo de hoy',
  goalAria: 'Elige un objetivo diario',
  minutes: n => `${n} min`,
  coachKicker: 'Tu entrenador',
  coachTitle: 'Dónde estás',
  trendAria: 'Progreso reciente',
  keyByKey: 'Tecla por tecla',
  heatTitle: 'Mapa de calor del teclado',
  heatText: 'Las teclas verdes son las que pulsas sin fallos, las ámbar a veces sí y a veces no, y las rojas te están quitando velocidad. Una tecla solo toma color cuando la has pulsado las veces suficientes como para decir algo útil.',
  heatEmpty: 'Todavía no hay datos suficientes — haz unas cuantas lecciones y vuelve.',
  heatAria: 'Precisión por tecla',
  courseKicker: 'El curso de {n} lecciones',
  resultsTitle: 'Cada lección, con su nota',
  resultsIntro: 'Tu mejor intento en cada lección, guardado en este dispositivo.',
  clear: 'Borrar el historial',
  columns: ['Lección', 'Pantallas hechas', 'Estrellas', 'Mejores PPM', 'Precisión'],
  keepGoing: 'No pares',
  nextTitle: 'Qué hacer ahora',
  courseCard: ['El curso completo', 'Todas las unidades en orden. Vuelve a una lección que quieras repetir o abre antes la unidad siguiente.', 'Ver el curso'],
  layoutsCard: ['Escribe en tu propio teclado', 'QWERTY, AZERTY, QWERTZ, devanagari, árabe, JIS — 119 distribuciones reales, y el curso sigue a la que elijas.', 'Ver las distribuciones']
};
