/* tien-do/text/fil.mjs — chữ TĨNH của trang tiến độ tiếng Filipino (/fil/pag-unlad/).
 * Cùng hình dạng với en.mjs; chữ JS điền lúc chạy nằm ở `progress` trong i18n/ui.fil.js. */
export default {
  slug: 'pag-unlad',
  title: 'Ang pag-unlad mo sa pagtitipa | TypingEase',
  description: 'Tingnan kung kumusta ang pagtitipa mo: ang marka ng bawat aralin, ang pinakamataas mong WPM at katumpakan, isang heat map ng mga key na madalas mong mamali, ang sunod-sunod mong araw at ang layunin mo sa araw-araw.',
  keepLearning: 'Ituloy ang pag-aaral',
  eyebrow: 'Kumusta ka na',
  h1: 'Ang pag-unlad mo sa pagtitipa',
  intro: 'Nakatago sa device na ito ang bawat numero sa pahinang ito, at hindi ipinapadala kahit saan. Magtipa ng isa pang aralin at magbabago ito.',
  courseSwitch: 'Kurso',
  overviewAria: 'Buod',
  sumLessons: 'Mga aralin na tapos',
  sumStars: 'Mga bituing naipon',
  sumWpm: 'Pinakamataas na WPM',
  sumAccuracy: 'Pinakamataas na katumpakan',
  milestones: 'Mga yugto',
  badgesTitle: 'Mga badge',
  badgesIntro: 'Nakatali ang bawat badge sa isang totoong numero sa talaan sa ibaba — walang ibang paraan para makuha ito kundi ang magtipa.',
  goalKicker: 'Layunin ngayong araw',
  goalAria: 'Pumili ng layunin sa araw-araw',
  minutes: n => `${n} min`,
  coachKicker: 'Ang coach mo',
  coachTitle: 'Nasaan ka na',
  trendAria: 'Kamakailang pag-unlad',
  keyByKey: 'Isa-isang key',
  heatTitle: 'Heat map ng keyboard',
  heatText: 'Berde ang mga key na malinis mong napipindot, dilaw ang minsang tama at minsang mali, at pula ang mga nagpapabagal sa iyo. Kinukulayan lang ang isang key kapag sapat na ang dami ng pagtipa mo rito para may masabi.',
  heatEmpty: 'Kulang pa ang datos — magtipa ng ilang aralin at bumalik dito.',
  heatAria: 'Katumpakan bawat key',
  courseKicker: 'Ang kursong may {n} aralin',
  resultsTitle: 'Ang marka ng bawat aralin',
  resultsIntro: 'Ang pinakamahusay mong ikot sa bawat aralin, nakatago sa device na ito.',
  clear: 'Burahin ang kasaysayan',
  columns: ['Aralin', 'Screen na tapos', 'Bituin', 'Pinakamataas na WPM', 'Katumpakan'],
  keepGoing: 'Ituloy lang',
  nextTitle: 'Ano ang susunod',
  courseCard: ['Ang buong kurso', 'Lahat ng yunit ayon sa pagkakasunod. Balikan ang araling gusto mong ulitin, o buksan nang maaga ang susunod na yunit.', 'Tingnan ang kurso'],
  layoutsCard: ['Magtipa sa sarili mong keyboard', 'QWERTY, AZERTY, QWERTZ, Devanagari, Arabic, JIS — 119 totoong layout, at sinusundan ng kurso ang pipiliin mo.', 'Tingnan ang mga layout']
};
