/* tien-do/text/fr.mjs — chữ TĨNH của trang tiến độ tiếng Pháp (cùng hình dạng với en.mjs).
 * `{n}` = số bài của khoá đang xem. */
export default {
  slug: 'progres',
  title: 'Tes progrès en dactylographie | TypingEase',
  description: 'Vois où tu en es : la note de chaque leçon, tes meilleurs MPM et ta meilleure précision, une carte de chaleur des touches que tu rates, ta série de jours et ton objectif quotidien.',
  keepLearning: 'Continuer à apprendre',
  eyebrow: 'Où tu en es',
  h1: 'Tes progrès en dactylographie',
  intro: "Tous les chiffres de cette page sont enregistrés sur cet appareil et ne partent nulle part. Fais une leçon de plus et ils se mettent à jour.",
  courseSwitch: 'Cours',
  overviewAria: "Vue d'ensemble",
  sumLessons: 'Leçons faites',
  sumStars: 'Étoiles réunies',
  sumWpm: 'Meilleurs MPM',
  sumAccuracy: 'Meilleure précision',
  milestones: 'Étapes franchies',
  badgesTitle: 'Badges',
  badgesIntro: "Chaque badge est lié à un vrai chiffre du tableau ci-dessous — la seule façon d'en débloquer un, c'est de taper.",
  goalKicker: "Objectif du jour",
  goalAria: 'Choisis un objectif quotidien',
  minutes: n => `${n} min`,
  coachKicker: 'Ton coach',
  coachTitle: 'Où tu en es',
  trendAria: 'Progrès récents',
  keyByKey: 'Touche par touche',
  heatTitle: 'Carte de chaleur du clavier',
  heatText: "Les touches vertes sont celles que tu frappes sans faute, les orange passent une fois sur deux, les rouges te font perdre de la vitesse. Une touche ne prend une couleur qu'une fois que tu l'as tapée assez souvent pour en dire quelque chose d'utile.",
  heatEmpty: "Pas encore assez de données — fais quelques leçons et reviens.",
  heatAria: 'Précision par touche',
  courseKicker: 'Le cours de {n} leçons',
  resultsTitle: 'Chaque leçon, notée',
  resultsIntro: 'Ton meilleur passage sur chaque leçon, gardé sur cet appareil.',
  clear: "Effacer l'historique",
  columns: ['Leçon', 'Écrans faits', 'Étoiles', 'Meilleurs MPM', 'Précision'],
  keepGoing: 'Continue',
  nextTitle: 'Et maintenant',
  courseCard: ['Le cours complet', "Toutes les unités dans l'ordre. Reviens sur une leçon que tu veux refaire, ou ouvre l'unité suivante en avance.", 'Voir le cours'],
  layoutsCard: ['Écris sur ton propre clavier', 'QWERTY, AZERTY, QWERTZ, devanagari, arabe, JIS — 119 dispositions réelles, et le cours suit celle que tu choisis.', 'Voir les dispositions']
};
