/* tien-do/text/id.mjs — chữ TĨNH của trang tiến độ tiếng Indonesia, cùng hình dạng với en.mjs.
 * Xưng "kamu", thuật ngữ khớp i18n/ui.id.js (pelajaran, unit, kursus, papan ketik, target harian, lencana, KPM). */
export default {
  slug: 'kemajuan',
  title: 'Kemajuan mengetikmu | TypingEase',
  description: 'Lihat perkembangan mengetikmu: nilai setiap pelajaran, KPM dan ketepatan terbaikmu, peta panas tombol yang sering salah, hari berturut-turutmu, dan target harianmu.',
  keepLearning: 'Terus belajar',
  eyebrow: 'Sejauh mana kamu',
  h1: 'Kemajuan mengetikmu',
  intro: 'Semua angka di halaman ini disimpan di perangkat ini dan tidak dikirim ke mana pun. Selesaikan satu pelajaran lagi dan angkanya ikut diperbarui.',
  courseSwitch: 'Kursus',
  overviewAria: 'Ringkasan',
  sumLessons: 'Pelajaran selesai',
  sumStars: 'Bintang terkumpul',
  sumWpm: 'KPM terbaik',
  sumAccuracy: 'Ketepatan terbaik',
  milestones: 'Pencapaian',
  badgesTitle: 'Lencana',
  badgesIntro: 'Setiap lencana terikat pada angka nyata di tabel di bawah — satu-satunya cara membukanya adalah dengan mengetik.',
  goalKicker: 'Target hari ini',
  goalAria: 'Pilih target harian',
  minutes: n => `${n} menit`,
  coachKicker: 'Pelatihmu',
  coachTitle: 'Posisimu sekarang',
  trendAria: 'Kemajuan terbaru',
  keyByKey: 'Tombol demi tombol',
  heatTitle: 'Peta panas papan ketik',
  heatText: 'Tombol hijau kamu tekan dengan mantap, tombol kuning kadang kena kadang meleset, dan tombol merah sedang memperlambatmu. Sebuah tombol baru diberi warna setelah cukup sering kamu ketik sehingga warnanya berarti.',
  heatEmpty: 'Datanya belum cukup — selesaikan beberapa pelajaran lalu kembali lagi.',
  heatAria: 'Ketepatan per tombol',
  courseKicker: 'Kursus {n} pelajaran',
  resultsTitle: 'Nilai setiap pelajaran',
  resultsIntro: 'Putaran terbaikmu di setiap pelajaran, tersimpan di perangkat ini.',
  clear: 'Hapus riwayat',
  columns: ['Pelajaran', 'Layar selesai', 'Bintang', 'KPM terbaik', 'Ketepatan'],
  keepGoing: 'Terus melangkah',
  nextTitle: 'Langkah berikutnya',
  courseCard: ['Kursus lengkap', 'Semua unit secara berurutan. Kembali ke pelajaran yang ingin kamu ulangi, atau buka unit berikutnya lebih awal.', 'Lihat kursus'],
  layoutsCard: ['Mengetik di papan ketikmu sendiri', 'QWERTY, AZERTY, QWERTZ, Dewanagari, Arab, JIS — 119 tata letak sungguhan, dan kursus mengikuti yang kamu pilih.', 'Lihat tata letaknya']
};
