/* tien-do/text/it.mjs — chữ TĨNH của trang tiến độ tiếng Ý (cùng hình dạng với en.mjs).
 * `{n}` = số bài của khoá đang xem. */
export default {
  slug: 'progressi',
  title: 'I tuoi progressi nella dattilografia | TypingEase',
  description: 'Guarda come stai andando: il punteggio di ogni lezione, le tue PPM e la tua precisione migliori, una mappa di calore dei tasti che sbagli, la tua serie di giorni e il tuo obiettivo giornaliero.',
  keepLearning: 'Continua a imparare',
  eyebrow: 'Come stai andando',
  h1: 'I tuoi progressi nella dattilografia',
  intro: 'Ogni numero di questa pagina è salvato su questo dispositivo e non viene inviato da nessuna parte. Fai ancora una lezione e si aggiorna.',
  courseSwitch: 'Corso',
  overviewAria: 'Riepilogo',
  sumLessons: 'Lezioni fatte',
  sumStars: 'Stelle raccolte',
  sumWpm: 'PPM migliori',
  sumAccuracy: 'Precisione migliore',
  milestones: 'Traguardi',
  badgesTitle: 'Distintivi',
  badgesIntro: "Ogni distintivo è legato a un numero vero della tabella qui sotto — l'unico modo per sbloccarlo è scrivere.",
  goalKicker: 'Obiettivo di oggi',
  goalAria: 'Scegli un obiettivo giornaliero',
  minutes: n => `${n} min`,
  coachKicker: 'Il tuo allenatore',
  coachTitle: 'Dove sei arrivato',
  trendAria: 'Progressi recenti',
  keyByKey: 'Tasto per tasto',
  heatTitle: 'Mappa di calore della tastiera',
  heatText: "I tasti verdi sono quelli che premi senza errori, quelli ambra a volte sì e a volte no, quelli rossi ti stanno costando velocità. Un tasto si colora solo quando l'hai premuto abbastanza volte da dire qualcosa di utile.",
  heatEmpty: 'Non ci sono ancora abbastanza dati — fai qualche lezione e torna qui.',
  heatAria: 'Precisione per tasto',
  courseKicker: 'Il corso da {n} lezioni',
  resultsTitle: 'Ogni lezione, con il suo punteggio',
  resultsIntro: 'Il tuo giro migliore in ogni lezione, salvato su questo dispositivo.',
  clear: 'Cancella la cronologia',
  columns: ['Lezione', 'Schermate fatte', 'Stelle', 'PPM migliori', 'Precisione'],
  keepGoing: 'Vai avanti',
  nextTitle: 'Cosa fare adesso',
  courseCard: ['Il corso completo', "Tutte le unità in ordine. Torna a una lezione che vuoi rifare, oppure apri prima l'unità successiva.", 'Vedi il corso'],
  layoutsCard: ['Scrivi sulla tua tastiera', 'QWERTY, AZERTY, QWERTZ, devanagari, arabo, JIS — 119 disposizioni vere, e il corso segue quella che scegli.', 'Vedi le disposizioni']
};
