/* tien-do/text/ja.mjs — chữ TĨNH của trang tiến độ tiếng Nhật (/ja/shinchoku/).
 * Cùng hình dạng với en.mjs — xem chú thích ở đó. `{n}` = số bài của khoá đang xem. */
export default {
  slug: 'shinchoku',
  title: 'タイピングの進み具合 | TypingEase',
  description: 'タイピングの進み具合をひと目で確認できます。レッスンごとの成績、最高 WPM と正確さ、よく間違えるキーのヒートマップ、連続日数と1日の目標。',
  keepLearning: '練習を続ける',
  eyebrow: 'いまの調子',
  h1: 'タイピングの進み具合',
  intro: 'このページの数字はすべてこの端末に保存され、どこにも送信されません。レッスンをもうひとつ終えると更新されます。',
  courseSwitch: 'コース',
  overviewAria: '概要',
  sumLessons: '終えたレッスン',
  sumStars: '集めた星',
  sumWpm: '最高 WPM',
  sumAccuracy: '最高の正確さ',
  milestones: 'これまでの記録',
  badgesTitle: 'バッジ',
  badgesIntro: 'どのバッジも下の表にある実際の数字と結びついています。手に入れる方法は、打つことだけです。',
  goalKicker: '今日の目標',
  goalAria: '1日の目標を選ぶ',
  minutes: n => `${n} 分`,
  coachKicker: 'コーチから',
  coachTitle: 'いまの位置',
  trendAria: '最近の伸び',
  keyByKey: 'キーごとに',
  heatTitle: 'キーボードのヒートマップ',
  heatText: '緑のキーは正確に打てているキー、黄色は当たり外れがあるキー、赤は速さを落としているキーです。意味のあることが言えるだけの回数を打ったキーにだけ色が付きます。',
  heatEmpty: 'まだデータが足りません。いくつかレッスンを終えてから、また見に来てください。',
  heatAria: 'キーごとの正確さ',
  courseKicker: '全 {n} レッスンのコース',
  resultsTitle: 'レッスンごとの成績',
  resultsIntro: '各レッスンでいちばんよかった回を、この端末に保存しています。',
  clear: '記録を消す',
  columns: ['レッスン', '終えた画面', '星', '最高 WPM', '正確さ'],
  keepGoing: 'この先へ',
  nextTitle: '次にすること',
  courseCard: ['コース全体', 'すべてのユニットを順番に。やり直したいレッスンに戻ることも、次のユニットを先に開くこともできます。', 'コースを見る'],
  layoutsCard: ['自分のキーボードで打つ', 'QWERTY、AZERTY、QWERTZ、デーヴァナーガリー、アラビア文字、JIS など、実在する 119 の配列。選んだ配列にコースが合わせます。', '配列を見る']
};
