/* tien-do/text/ko.mjs — chữ TĨNH của trang tiến độ tiếng Hàn (/ko/jindo/), 해요체.
 * Cùng hình dạng với en.mjs — xem chú thích ở đó. `{n}` = số bài của khoá đang xem. */
export default {
  slug: 'jindo',
  title: '내 타자 진도 | TypingEase',
  description: '타자 연습이 어떻게 되고 있는지 확인하세요. 과마다 받은 점수, 최고 WPM과 정확도, 자주 틀리는 키를 보여 주는 히트맵, 연속 기록과 하루 목표까지 볼 수 있어요.',
  keepLearning: '계속 배우기',
  eyebrow: '지금 어디쯤인지',
  h1: '내 타자 진도',
  intro: '이 페이지의 숫자는 모두 이 기기에만 저장되고 어디로도 보내지 않아요. 한 과를 더 치면 바로 바뀌어요.',
  courseSwitch: '강의',
  overviewAria: '한눈에 보기',
  sumLessons: '마친 과',
  sumStars: '모은 별',
  sumWpm: '최고 WPM',
  sumAccuracy: '최고 정확도',
  milestones: '이정표',
  badgesTitle: '배지',
  badgesIntro: '배지마다 아래 표에 있는 실제 숫자가 걸려 있어요. 배지를 여는 방법은 직접 치는 것뿐이에요.',
  goalKicker: '오늘의 목표',
  goalAria: '하루 목표 고르기',
  minutes: n => `${n}분`,
  coachKicker: '코치',
  coachTitle: '지금 내 자리',
  trendAria: '최근 변화',
  keyByKey: '키 하나하나',
  heatTitle: '자판 히트맵',
  heatText: '초록색 키는 깔끔하게 치는 키, 노란색 키는 맞았다 틀렸다 하는 키, 빨간색 키는 속도를 잡아먹는 키예요. 의미 있는 말을 할 수 있을 만큼 친 키에만 색이 칠해져요.',
  heatEmpty: '아직 데이터가 부족해요. 몇 과를 친 다음 다시 와 보세요.',
  heatAria: '키별 정확도',
  courseKicker: '{n}개 과 강의',
  resultsTitle: '과마다 받은 점수',
  resultsIntro: '과마다 가장 잘 친 기록을 이 기기에 저장해요.',
  clear: '기록 지우기',
  columns: ['과', '마친 화면', '별', '최고 WPM', '정확도'],
  keepGoing: '계속 나아가기',
  nextTitle: '다음에 할 일',
  courseCard: ['전체 강의', '모든 단원을 차례대로 볼 수 있어요. 다시 하고 싶은 과로 돌아가거나 다음 단원을 먼저 열어 보세요.', '강의 보기'],
  layoutsCard: ['내 자판으로 치기', 'QWERTY, AZERTY, QWERTZ, 데바나가리, 아랍어, JIS 등 실제 배열 119개. 고른 배열에 맞춰 강의가 따라가요.', '배열 보기']
};
