/* tien-do/text/ms.mjs — chữ TĨNH của trang tiến độ tiếng Mã Lai, cùng hình dạng với en.mjs.
 * Xưng "anda", thuật ngữ khớp i18n/ui.ms.js (pelajaran, unit, kursus, papan kekunci, sasaran harian, lencana, PSM). */
export default {
  slug: 'kemajuan',
  title: 'Kemajuan menaip anda | TypingEase',
  description: 'Lihat perkembangan menaip anda: markah setiap pelajaran, PSM dan ketepatan terbaik anda, peta haba kekunci yang kerap tersilap, hari berturut-turut anda dan sasaran harian anda.',
  keepLearning: 'Terus belajar',
  eyebrow: 'Prestasi anda',
  h1: 'Kemajuan menaip anda',
  intro: 'Setiap angka pada halaman ini disimpan dalam peranti ini dan tidak dihantar ke mana-mana. Taip satu pelajaran lagi dan angkanya akan dikemas kini.',
  courseSwitch: 'Kursus',
  overviewAria: 'Gambaran keseluruhan',
  sumLessons: 'Pelajaran selesai',
  sumStars: 'Bintang dikumpul',
  sumWpm: 'PSM terbaik',
  sumAccuracy: 'Ketepatan terbaik',
  milestones: 'Pencapaian',
  badgesTitle: 'Lencana',
  badgesIntro: 'Setiap lencana terikat pada angka sebenar dalam jadual di bawah — satu-satunya cara untuk membukanya ialah dengan menaip.',
  goalKicker: 'Sasaran hari ini',
  goalAria: 'Pilih sasaran harian',
  minutes: n => `${n} min`,
  coachKicker: 'Jurulatih anda',
  coachTitle: 'Di mana anda sekarang',
  trendAria: 'Kemajuan terkini',
  keyByKey: 'Kekunci demi kekunci',
  heatTitle: 'Peta haba papan kekunci',
  heatText: 'Kekunci hijau ialah yang anda tekan dengan tepat, kekunci kuning kadang-kadang kena dan kadang-kadang tersasar, dan kekunci merah sedang memperlahankan anda. Sesuatu kekunci hanya diwarnakan selepas anda menaipnya cukup kerap sehingga warnanya bermakna.',
  heatEmpty: 'Data belum mencukupi — taip beberapa pelajaran dan kembali semula.',
  heatAria: 'Ketepatan setiap kekunci',
  courseKicker: 'Kursus {n} pelajaran',
  resultsTitle: 'Markah setiap pelajaran',
  resultsIntro: 'Pusingan terbaik anda bagi setiap pelajaran, disimpan dalam peranti ini.',
  clear: 'Padam sejarah',
  columns: ['Pelajaran', 'Skrin selesai', 'Bintang', 'PSM terbaik', 'Ketepatan'],
  keepGoing: 'Teruskan',
  nextTitle: 'Langkah seterusnya',
  courseCard: ['Kursus penuh', 'Semua unit mengikut urutan. Kembali ke pelajaran yang mahu anda ulang, atau buka unit seterusnya lebih awal.', 'Lihat kursus'],
  layoutsCard: ['Menaip pada papan kekunci anda sendiri', 'QWERTY, AZERTY, QWERTZ, Devanagari, Arab, JIS — 119 susun atur sebenar di laman ini. Kursus bahasa Melayu ini dibina untuk QWERTY.', 'Lihat susun atur']
};
