/* tien-do/text/nl.mjs — chữ TĨNH của trang tiến độ tiếng Hà Lan (/nl/voortgang/), cùng hình dạng
 * với en.mjs. Chữ JS điền lúc chạy nằm ở `progress` trong i18n/ui.nl.js. `{n}` = số bài. */
export default {
  slug: 'voortgang',
  title: 'Je voortgang met blind typen | TypingEase',
  description: 'Zie hoe je typen vordert: elke les met een score, je beste WPM en nauwkeurigheid, een heatmap van de toetsen waarop je misslaat, je reeks dagen en je dagdoel.',
  keepLearning: 'Verder leren',
  eyebrow: 'Hoe het met je gaat',
  h1: 'Je voortgang met blind typen',
  intro: 'Alle cijfers op deze pagina staan alleen op dit apparaat en gaan nergens naartoe. Typ nog een les en ze worden bijgewerkt.',
  courseSwitch: 'Cursus',
  overviewAria: 'Overzicht',
  sumLessons: 'Lessen afgerond',
  sumStars: 'Sterren verzameld',
  sumWpm: 'Beste WPM',
  sumAccuracy: 'Beste nauwkeurigheid',
  milestones: 'Mijlpalen',
  badgesTitle: 'Badges',
  badgesIntro: 'Elke badge hangt aan een echt getal uit de tabel hieronder — je krijgt er alleen een door te typen.',
  goalKicker: 'Dagdoel',
  goalAria: 'Kies een dagdoel',
  minutes: n => `${n} min`,
  coachKicker: 'Je coach',
  coachTitle: 'Waar je staat',
  trendAria: 'Recente voortgang',
  keyByKey: 'Toets voor toets',
  heatTitle: 'Heatmap van het toetsenbord',
  heatText: 'Groene toetsen raak je netjes, oranje toetsen nu eens wel en dan weer niet, en rode kosten je snelheid. Een toets krijgt pas een kleur als je hem vaak genoeg hebt getypt om er iets zinnigs over te zeggen.',
  heatEmpty: 'Nog niet genoeg gegevens — typ een paar lessen en kom dan terug.',
  heatAria: 'Nauwkeurigheid per toets',
  courseKicker: 'De cursus van {n} lessen',
  resultsTitle: 'Elke les met een score',
  resultsIntro: 'Je beste ronde in elke les, bewaard op dit apparaat.',
  clear: 'Geschiedenis wissen',
  columns: ['Les', 'Schermen afgerond', 'Sterren', 'Beste WPM', 'Nauwkeurigheid'],
  keepGoing: 'Ga door',
  nextTitle: 'Wat je nu kunt doen',
  courseCard: ['De hele cursus', 'Alle units op volgorde. Doe een les nog eens over, of open de volgende unit alvast.', 'Bekijk de cursus'],
  layoutsCard: ['Typ op je eigen toetsenbord', 'QWERTY, AZERTY, QWERTZ, devanagari, Arabisch, JIS — 119 echte indelingen, en de cursus volgt de indeling die je kiest.', 'Bekijk de indelingen']
};
