/* tien-do/text/pl.mjs — chữ TĨNH của trang tiến độ tiếng Ba Lan (/pl/postepy/), cùng hình dạng
 * với en.mjs. Chữ JS điền lúc chạy nằm ở `progress` trong i18n/ui.pl.js. `{n}` = số bài. */
export default {
  slug: 'postepy',
  title: 'Twoje postępy w pisaniu bezwzrokowym | TypingEase',
  description: 'Zobacz, jak idzie ci pisanie: wynik każdej lekcji, najlepsza szybkość i dokładność, mapa cieplna klawiszy, na których się mylisz, seria dni z rzędu i dzienny cel.',
  keepLearning: 'Ucz się dalej',
  eyebrow: 'Jak ci idzie',
  h1: 'Twoje postępy w pisaniu bezwzrokowym',
  intro: 'Wszystkie liczby na tej stronie są zapisane tylko na tym urządzeniu i nigdzie nie są wysyłane. Przepisz jeszcze jedną lekcję, a się zaktualizują.',
  courseSwitch: 'Kurs',
  overviewAria: 'Podsumowanie',
  sumLessons: 'Ukończone lekcje',
  sumStars: 'Zebrane gwiazdki',
  sumWpm: 'Najlepsze WPM',
  sumAccuracy: 'Najlepsza dokładność',
  milestones: 'Kamienie milowe',
  badgesTitle: 'Odznaki',
  badgesIntro: 'Każda odznaka jest związana z prawdziwą liczbą z tabeli poniżej — zdobyć ją można tylko pisaniem.',
  goalKicker: 'Cel na dziś',
  goalAria: 'Wybierz dzienny cel',
  minutes: n => `${n} min`,
  coachKicker: 'Twój trener',
  coachTitle: 'Gdzie jesteś',
  trendAria: 'Ostatnie postępy',
  keyByKey: 'Klawisz po klawiszu',
  heatTitle: 'Mapa cieplna klawiatury',
  heatText: 'Zielone klawisze trafiasz czysto, żółte raz tak, raz nie, a czerwone kosztują cię szybkość. Klawisz dostaje kolor dopiero wtedy, gdy napiszesz go tyle razy, że liczba zaczyna coś mówić.',
  heatEmpty: 'Za mało danych — przepisz kilka lekcji i wróć tutaj.',
  heatAria: 'Dokładność dla każdego klawisza',
  courseKicker: 'Kurs · lekcje: {n}',
  resultsTitle: 'Wynik każdej lekcji',
  resultsIntro: 'Twoje najlepsze przejście każdej lekcji, zapisane na tym urządzeniu.',
  clear: 'Wyczyść historię',
  columns: ['Lekcja', 'Ukończone ekrany', 'Gwiazdki', 'Najlepsze WPM', 'Dokładność'],
  keepGoing: 'Idź dalej',
  nextTitle: 'Co dalej',
  courseCard: ['Cały kurs', 'Wszystkie części po kolei. Wróć do lekcji, którą chcesz powtórzyć, albo otwórz wcześniej następną część.', 'Zobacz kurs'],
  layoutsCard: ['Pisz na własnej klawiaturze', 'QWERTZ, QWERTY, AZERTY, dewanagari, arabska, JIS — 119 prawdziwych układów, a kurs dopasowuje się do tego, który wybierzesz.', 'Zobacz układy']
};
