/* tien-do/text/pt.mjs — chữ TĨNH của trang tiến độ tiếng Bồ Đào Nha (Brasil), cùng hình dạng với en.mjs.
 * Xưng "você", thuật ngữ khớp i18n/ui.pt.js (lição, unidade, curso, meta diária, medalha, PPM). */
export default {
  slug: 'progresso',
  title: 'O seu progresso na digitação | TypingEase',
  description: 'Veja como vai a sua digitação: a nota de cada lição, as suas melhores PPM e precisão, um mapa de calor das teclas que você mais erra, os seus dias seguidos e a sua meta diária.',
  keepLearning: 'Continuar aprendendo',
  eyebrow: 'Como você está indo',
  h1: 'O seu progresso na digitação',
  intro: 'Todos os números desta página ficam guardados neste aparelho e não são enviados para lugar nenhum. Faça mais uma lição e eles se atualizam.',
  courseSwitch: 'Curso',
  overviewAria: 'Visão geral',
  sumLessons: 'Lições feitas',
  sumStars: 'Estrelas conquistadas',
  sumWpm: 'Melhor PPM',
  sumAccuracy: 'Melhor precisão',
  milestones: 'Conquistas',
  badgesTitle: 'Medalhas',
  badgesIntro: 'Cada medalha depende de um número de verdade da tabela abaixo — o único jeito de ganhar uma é digitando.',
  goalKicker: 'Meta de hoje',
  goalAria: 'Escolha uma meta diária',
  minutes: n => `${n} min`,
  coachKicker: 'O seu treinador',
  coachTitle: 'Onde você está',
  trendAria: 'Progresso recente',
  keyByKey: 'Tecla por tecla',
  heatTitle: 'Mapa de calor do teclado',
  heatText: 'As teclas verdes são as que você acerta com segurança, as amarelas às vezes acerta, às vezes não, e as vermelhas estão custando velocidade. Uma tecla só ganha cor depois que você a digitou vezes suficientes para a cor dizer alguma coisa.',
  heatEmpty: 'Ainda não há dados suficientes — faça algumas lições e volte aqui.',
  heatAria: 'Precisão por tecla',
  courseKicker: 'O curso de {n} lições',
  resultsTitle: 'A nota de cada lição',
  resultsIntro: 'A sua melhor volta em cada lição, guardada neste aparelho.',
  clear: 'Apagar o histórico',
  columns: ['Lição', 'Telas feitas', 'Estrelas', 'Melhor PPM', 'Precisão'],
  keepGoing: 'Siga em frente',
  nextTitle: 'O que fazer agora',
  courseCard: ['O curso completo', 'Todas as unidades em ordem. Volte a uma lição que você quer refazer ou abra a próxima unidade antes da hora.', 'Ver o curso'],
  layoutsCard: ['Digite no seu próprio teclado', 'QWERTY, AZERTY, QWERTZ, devanágari, árabe, JIS — 119 layouts reais, e o curso acompanha o que você escolher.', 'Ver os layouts']
};
