/* tien-do/text/sw.mjs — chữ TĨNH của trang tiến độ tiếng Swahili (/sw/maendeleo/).
 * Cùng hình dạng với en.mjs; chữ JS điền lúc chạy nằm ở `progress` trong i18n/ui.sw.js. */
export default {
  slug: 'maendeleo',
  title: 'Maendeleo yako ya kuandika | TypingEase',
  description: 'Ona unavyoendelea katika kuandika: alama za kila somo, WPM yako bora na usahihi wako bora, ramani ya joto ya vitufe unavyokosea, siku zako mfululizo na lengo lako la kila siku.',
  keepLearning: 'Endelea kujifunza',
  eyebrow: 'Unavyoendelea',
  h1: 'Maendeleo yako ya kuandika',
  intro: 'Kila namba kwenye ukurasa huu imehifadhiwa kwenye kifaa hiki na haitumwi popote. Andika somo moja zaidi na itabadilika.',
  courseSwitch: 'Kozi',
  overviewAria: 'Muhtasari',
  sumLessons: 'Masomo yaliyokamilika',
  sumStars: 'Nyota zilizokusanywa',
  sumWpm: 'WPM bora',
  sumAccuracy: 'Usahihi bora',
  milestones: 'Hatua muhimu',
  badgesTitle: 'Beji',
  badgesIntro: 'Kila beji imefungamana na namba halisi kwenye jedwali lililo hapa chini — hakuna njia ya kuipata isipokuwa kwa kuandika.',
  goalKicker: 'Lengo la leo',
  goalAria: 'Chagua lengo la kila siku',
  minutes: n => `dakika ${n}`,
  coachKicker: 'Kocha wako',
  coachTitle: 'Ulipo sasa',
  trendAria: 'Maendeleo ya karibuni',
  keyByKey: 'Kitufe kwa kitufe',
  heatTitle: 'Ramani ya joto ya kibodi',
  heatText: 'Vitufe vya kijani ni vile unavyobonyeza bila kosa, vya manjano ni vya kubahatisha, na vyekundu ndivyo vinavyokupunguzia kasi. Kitufe hupewa rangi tu baada ya kukiandika mara za kutosha kusema jambo la maana.',
  heatEmpty: 'Bado hakuna data ya kutosha — andika masomo machache kisha urudi.',
  heatAria: 'Usahihi kwa kila kitufe',
  courseKicker: 'Kozi ya masomo {n}',
  resultsTitle: 'Alama za kila somo',
  resultsIntro: 'Mzunguko wako bora katika kila somo, umehifadhiwa kwenye kifaa hiki.',
  clear: 'Futa historia',
  columns: ['Somo', 'Skrini zilizokamilika', 'Nyota', 'WPM bora', 'Usahihi'],
  keepGoing: 'Endelea mbele',
  nextTitle: 'Nini kinafuata',
  courseCard: ['Kozi nzima', 'Vitengo vyote kwa mpangilio. Rudia somo unalotaka kulifanya tena, au fungua kitengo kinachofuata mapema.', 'Tazama kozi'],
  layoutsCard: ['Andika kwenye kibodi yako mwenyewe', 'QWERTY, AZERTY, QWERTZ, Devanagari, Kiarabu, JIS — mipangilio halisi 119, na kozi inafuata ule utakaouchagua.', 'Tazama mipangilio']
};
