/* tien-do/text/tr.mjs — chữ TĨNH của trang tiến độ tiếng Thổ (/tr/ilerleme/).
 * Cùng hình dạng với en.mjs; chữ JS điền lúc chạy nằm ở `progress` trong i18n/ui.tr.js. */
export default {
  slug: 'ilerleme',
  title: 'Klavyedeki ilerlemen | TypingEase',
  description: 'Yazmanın nasıl gittiğini gör: her dersin puanı, en iyi KDK ve doğruluk değerin, en çok hangi tuşlarda yanıldığını gösteren bir ısı haritası, günlük serin ve günlük hedefin.',
  keepLearning: 'Öğrenmeye devam et',
  eyebrow: 'Nasıl gidiyorsun',
  h1: 'Klavyedeki ilerlemen',
  intro: 'Bu sayfadaki her sayı bu cihazda saklanır ve hiçbir yere gönderilmez. Bir ders daha yaz, sayfa güncellensin.',
  courseSwitch: 'Kurs',
  overviewAria: 'Genel bakış',
  sumLessons: 'Biten dersler',
  sumStars: 'Toplanan yıldızlar',
  sumWpm: 'En iyi KDK',
  sumAccuracy: 'En iyi doğruluk',
  milestones: 'Kilometre taşları',
  badgesTitle: 'Rozetler',
  badgesIntro: 'Her rozet aşağıdaki tablodaki gerçek bir sayıya bağlı — birini açmanın yazmaktan başka yolu yok.',
  goalKicker: 'Bugünkü hedef',
  goalAria: 'Günlük hedef seç',
  minutes: n => `${n} dk`,
  coachKicker: 'Koçun',
  coachTitle: 'Neredesin',
  trendAria: 'Son ilerleme',
  keyByKey: 'Tuş tuş',
  heatTitle: 'Klavye ısı haritası',
  heatText: 'Yeşil tuşlar temiz bastıkların, sarılar bazen tutup bazen kaçanlar, kırmızılar ise sana hız kaybettirenler. Bir tuş ancak onu işe yarar bir şey söyleyecek kadar çok yazdıktan sonra renklenir.',
  heatEmpty: 'Henüz yeterli veri yok — birkaç ders yaz ve geri gel.',
  heatAria: 'Tuş başına doğruluk',
  courseKicker: '{n} derslik kurs',
  resultsTitle: 'Her dersin puanı',
  resultsIntro: 'Her dersteki en iyi turun, bu cihazda saklanır.',
  clear: 'Geçmişi temizle',
  columns: ['Ders', 'Biten ekranlar', 'Yıldız', 'En iyi KDK', 'Doğruluk'],
  keepGoing: 'Devam et',
  nextTitle: 'Sırada ne var',
  courseCard: ['Kursun tamamı', 'Bütün üniteler sırayla. Yeniden yapmak istediğin bir derse dön ya da sonraki üniteyi erkenden aç.', 'Kursu gör'],
  layoutsCard: ['Kendi klavyende yaz', 'QWERTY, AZERTY, QWERTZ, Türkçe F, devanagari, Arapça, JIS — 119 gerçek klavye düzeni, ve kurs seçtiğin düzeni izler.', 'Düzenleri gör']
};
