/* tien-do/text/zh-tw.mjs — chữ TĨNH của trang tiến độ tiếng Trung phồn thể (/zh-tw/jindu/).
 * Cùng hình dạng với en.mjs — xem chú thích ở đó. `{n}` = số bài của khoá đang xem. */
export default {
  slug: 'jindu',
  title: '你的打字進度 | TypingEase',
  description: '看看你的打字練得怎麼樣：每一課的成績、最好的 WPM 和準確率、哪些鍵最常打錯的熱度圖，還有連續天數和每日目標。',
  keepLearning: '繼續學習',
  eyebrow: '你練得怎麼樣',
  h1: '你的打字進度',
  intro: '這個頁面上的每個數字都只儲存在這台裝置上，不會傳送到任何地方。再練一課，它就會更新。',
  courseSwitch: '課程',
  overviewAria: '總覽',
  sumLessons: '已完成的課',
  sumStars: '獲得的星星',
  sumWpm: '最好的 WPM',
  sumAccuracy: '最高準確率',
  milestones: '里程碑',
  badgesTitle: '徽章',
  badgesIntro: '每個徽章都對應下面表格裡一個真實的數字，想拿到它，只有靠打字。',
  goalKicker: '今天的目標',
  goalAria: '選擇每日目標',
  minutes: n => `${n} 分鐘`,
  coachKicker: '你的教練',
  coachTitle: '你現在的程度',
  trendAria: '最近的進步',
  keyByKey: '逐鍵查看',
  heatTitle: '鍵盤熱度圖',
  heatText: '綠色的鍵你打得又準又穩，黃色的鍵時對時錯，紅色的鍵正在拖慢你的速度。一個鍵要打夠一定次數、資料有意義了，才會顯示顏色。',
  heatEmpty: '資料還不夠。先練幾課，再回來看看。',
  heatAria: '每個鍵的準確率',
  courseKicker: '{n} 課的課程',
  resultsTitle: '每一課的成績',
  resultsIntro: '每一課你最好的一次，儲存在這台裝置上。',
  clear: '清除紀錄',
  columns: ['課', '已完成的頁', '星星', '最好的 WPM', '準確率'],
  keepGoing: '繼續前進',
  nextTitle: '接下來做什麼',
  courseCard: ['完整課程', '按順序排好的所有單元。回頭重練想再打一遍的課，或者提前打開下一個單元。', '查看課程'],
  layoutsCard: ['在你自己的鍵盤上打字', 'QWERTY、AZERTY、QWERTZ、注音、天城文、阿拉伯文、JIS——119 種真實的鍵盤配置，課程會跟著你選的配置走。', '查看鍵盤配置']
};
