/* tien-do/text/zh.mjs — chữ TĨNH của trang tiến độ tiếng Trung giản thể (/zh/jindu/).
 * Cùng hình dạng với en.mjs — xem chú thích ở đó. `{n}` = số bài của khoá đang xem. */
export default {
  slug: 'jindu',
  title: '你的打字进度 | TypingEase',
  description: '看看你的打字练得怎么样：每一课的成绩、最好的 WPM 和准确率、哪些键最常打错的热力图，还有连续天数和每日目标。',
  keepLearning: '继续学习',
  eyebrow: '你练得怎么样',
  h1: '你的打字进度',
  intro: '这个页面上的每个数字都只保存在这台设备上，不会发送到任何地方。再练一课，它就会更新。',
  courseSwitch: '课程',
  overviewAria: '概览',
  sumLessons: '已完成的课',
  sumStars: '获得的星星',
  sumWpm: '最好的 WPM',
  sumAccuracy: '最高准确率',
  milestones: '里程碑',
  badgesTitle: '徽章',
  badgesIntro: '每个徽章都对应下面表格里一个真实的数字，想拿到它，只有靠打字。',
  goalKicker: '今天的目标',
  goalAria: '选择每日目标',
  minutes: n => `${n} 分钟`,
  coachKicker: '你的教练',
  coachTitle: '你现在的水平',
  trendAria: '最近的进步',
  keyByKey: '逐键查看',
  heatTitle: '键盘热力图',
  heatText: '绿色的键你打得又准又稳，黄色的键时对时错，红色的键正在拖慢你的速度。一个键要打够一定次数、数据有意义了，才会显示颜色。',
  heatEmpty: '数据还不够。先练几课，再回来看看。',
  heatAria: '每个键的准确率',
  courseKicker: '{n} 课的课程',
  resultsTitle: '每一课的成绩',
  resultsIntro: '每一课你最好的一次，保存在这台设备上。',
  clear: '清除记录',
  columns: ['课', '已完成的屏', '星星', '最好的 WPM', '准确率'],
  keepGoing: '继续前进',
  nextTitle: '接下来做什么',
  courseCard: ['完整课程', '按顺序排好的所有单元。回头重练想再打一遍的课，或者提前打开下一个单元。', '查看课程'],
  layoutsCard: ['在你自己的键盘上打字', 'QWERTY、AZERTY、QWERTZ、天城文、阿拉伯文、JIS——119 种真实的键盘布局，课程会跟着你选的布局走。', '查看键盘布局']
};
